version: '3.8'

services:
  db:
    container_name: medical_db_container
    image: ankane/pgvector:latest
    ports:
      - "5433:5432"  # <--- WE CHANGED THIS TO 5433
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=medical_rag
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: